# Generated by Django 4.2.7 on 2023-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0042_finalfeedback_userselectionfeedback_parent1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DalleError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.UUIDField(blank=True, default=None, null=True)),
                ('iteration', models.IntegerField(blank=True, null=True)),
                ('instance', models.CharField(blank=True, max_length=8)),
                ('user_input', models.TextField(blank=True)),
                ('attributes', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
            ],
        ),
    ]
